repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      exclude: migrations
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      additional_dependencies: [flake8-blind-except,flake8-bugbear,flake8-builtins,flake8-debugger,
                                flake8-print,flake8-quotes,flake8-todo,flake8-variables-names,pep8-naming,
                                flake8-per-file-ignores, flake8-docstrings, flake8-rst-docstrings]
