version: '3'

services:
#  db:
#    ports:
#      - "5432:5432"
#    image: postgres
#    environment:
#      POSTGRES_DB: "combat_tarczylo"
#      POSTGRES_USER: "postgres"
#    volumes:
#      - "/var/lib/postgresql/data"
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/combat_tarczylo
      ports:
        - "8000:8000"
#    depends_on:
#      - combat_tarczylo