version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "combat_tarczylo"
      POSTGRES_USER: "postgres"
    volumes:
      - "/var/lib/postgresql/data"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py makemigrations
            python manage.py migrate
            python manage.py init_db local
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/combat_tarczylo
    ports:
      - "8000:8000"
    depends_on:
      - db