# Generated by Django 3.0.5 on 2020-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantmessage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
