# Generated by Django 3.0.5 on 2020-04-28 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 15, 36, 764355, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 15, 36, 766924, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 15, 36, 774559, tzinfo=utc), null=True),
        ),
    ]
