# Generated by Django 3.0.5 on 2020-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_importantmessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='have_paid',
            field=models.BooleanField(default=False),
        ),
    ]
