# Generated by Django 3.0.5 on 2020-04-26 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200426_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 22, 42, 29, 970107, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 22, 42, 29, 972903, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 22, 42, 29, 978249, tzinfo=utc), null=True),
        ),
    ]
