# Generated by Django 3.0.5 on 2020-05-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_member_have_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
