# Generated by Django 3.0.5 on 2020-04-28 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 20, 47, 375834, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 20, 47, 378542, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 20, 47, 383480, tzinfo=utc), null=True),
        ),
    ]
