# Generated by Django 3.0.5 on 2020-04-28 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200428_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 30, 52, 369345, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 30, 52, 375326, tzinfo=utc), null=True),
        ),
    ]
