# Generated by Django 3.0.5 on 2020-05-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='media/default.png', null=True, upload_to=''),
        ),
    ]
