# Generated by Django 3.0.5 on 2020-04-29 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200428_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 29, 13, 36, 2, 613431, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 29, 13, 36, 2, 623568, tzinfo=utc), null=True),
        ),
    ]
