# Generated by Django 3.0.5 on 2020-04-29 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200429_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importantmessage',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 29, 13, 57, 33, 722198, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 29, 13, 57, 33, 729758, tzinfo=utc), null=True),
        ),
    ]
