# Generated by Django 3.0.5 on 2020-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200528_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="picture",
            field=models.ImageField(default="default.png", null=True, upload_to=""),
        ),
    ]
