# Generated by Django 3.0.5 on 2020-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200528_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
