# Generated by Django 3.0.5 on 2020-04-29 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200429_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
