# Generated by Django 3.0.5 on 2020-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20200528_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
