# Generated by Django 3.0.5 on 2020-04-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
