# Generated by Django 3.0.5 on 2020-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20200528_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
