# Generated by Django 3.0.5 on 2020-04-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='time_table',
            field=models.ManyToManyField(null=True, to='api.TimeTable'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_table',
            field=models.ManyToManyField(null=True, to='api.TimeTable'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Instructor'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='time_table',
            field=models.ManyToManyField(null=True, to='api.TimeTable'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='api.Product'),
        ),
    ]
