# Generated by Django 3.0.5 on 2020-06-17 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20200617_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="place",
            field=models.CharField(blank=True, default="In club", max_length=255),
        ),
        migrations.AlterField(
            model_name="internship",
            name="date_begin",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2020, 6, 17, 20, 21, 6, 538878)
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="place",
            field=models.CharField(blank=True, default="In club", max_length=255),
        ),
    ]
