# Generated by Django 3.0.8 on 2020-07-02 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_auto_20200702_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="date_begin",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2020, 7, 2, 22, 58, 3, 7214)
            ),
        ),
    ]
