# Generated by Django 3.0.8 on 2020-07-02 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_auto_20200702_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="date_begin",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2020, 7, 2, 23, 8, 16, 71067)
            ),
        ),
    ]
