# Generated by Django 3.0.8 on 2020-07-02 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_auto_20200702_2308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="date_begin",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2020, 7, 2, 23, 11, 22, 405617)
            ),
        ),
    ]
