# Generated by Django 3.0.8 on 2020-07-03 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_auto_20200702_2311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="date_begin",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2020, 7, 3, 12, 16, 47, 311503)
            ),
        ),
    ]
