# Generated by Django 3.0.8 on 2020-07-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200703_1245'),
        ('api', '0032_auto_20200703_1217'),
    ]

    operations = [
    ]
