# Generated by Django 3.0.8 on 2020-07-03 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20200703_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date_begin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 12, 59, 0, 68608)),
        ),
    ]
