# Generated by Django 3.0.8 on 2020-07-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_auto_20200703_2253"),
        ("api", "0037_auto_20200703_1529"),
    ]

    operations = []
